#!/bin/bash

/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.0
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.1
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.2
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.3
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.4
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.5
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.6
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.7
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.8
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 0.9
/home/haris/miniconda3/envs/myenv/bin/python /home/haris/project/backtester/run.py --scores_path /home/haris/mymodel/predictions/StockPredictor_20251231_merged.csv,/home/haris/mymodel_10/predictions/StockPredictor_20260306_merged.csv --trade_support 7 --mix_coefficient 1.0
